### ISSUE TITLE
[Enhancement] Allow client to fetch config from server

### ISSUE THREAD

**Issue by slvnperron** [botpress/botpress-platform-webchat#43]
Instead of passing very long urls like: 

```
http://localhost:3000/lite/?m=platform-webchat&options=%7B%22config%22%3A%7B%22botName%22%3A%22ANDi%22%2C%22botAvatarUrl%22%3A%22%22%2C%22botConvoTitle%22%3A%22ANDi%22%2C%22botConvoDescription%22%3A%22Ask%20me%20anything%2C%20I%27m%20here%20to%20help%21%22%2C%22backgroundColor%22%3A%22%23ffffff%22%2C%22textColorOnBackground%22%3A%22%23666666%22%2C%22foregroundColor%22%3A%22%23000000%22%2C%22textColorOnForeground%22%3A%22%23ffffff%22%7D%7D&v=fullscreen
```

We should be able to pass a "preset=name1"

Then on the server side we can define name1:

```yaml
# inside botpress-platform-webchat.config.yaml

presets:
  name1:
    botName: 'ANDi'
    # etc...
```
